### ISSUE TITLE
Too large embedding files

### ISSUE THREAD

**Issue by quhfus** [quhfus/DoSeR-Disambiguation#1]
Create smaller embedding files (especially Doc2Vec). Disambiguation accuracy may be decrease slightly.

**Comment by shauryr** [comment]
I get an error when I try to untar the file. << invalid compressed data--crc error >> Some files WikiEntityModel_400_neg10_iter5, doc2vec_wiki_model.d2v are correctly downloaded but extracting doc2vec_wiki_model.d2v.syn0.npy gives an error. 
Can you please upload different parts of the tar separately. Downloading such a huge file often fails and I have to resume from somewhere between, which I suppose corrupts the file. I am using wget -c for downloading.

**Comment by quhfus** [comment]
Will be fixed the next days!
